DROP TABLE YOON.T_ORDER42;
CREATE TABLE YOON.T_ORDER42
 (  ORDER_NO      VARCHAR2(7)
  , CUST_NO       VARCHAR2(7)
  , GOODS_NO      VARCHAR2(7)
  , ORDER_DT      VARCHAR2(8)
  , ORDER_AMT     NUMBER
  , ORDER_QTY     NUMBER
  , ORDER_CD      VARCHAR2(5)
  , CONSTRAINT PK_T_ORDER42 PRIMARY KEY (ORDER_NO)
  )
;

CREATE PUBLIC SYNONYM T_ORDER42 FOR YOON.T_ORDER42;

INSERT /*+ APPEND */ INTO T_ORDER42
SELECT LPAD(TO_CHAR(ROWNUM), 7, '0')        ORDER_NO
    ,  LPAD(TO_CHAR(ROWNUM), 7, '0')        CUST_NO
    ,  LPAD(TO_CHAR(ROWNUM), 7, '0')        GOODS_NO
    ,  TO_CHAR(SYSDATE-ROWNUM, 'YYYYMMDD')  ORDER_DT
    ,  ROWNUM                               ORDER_AMT 
    ,  MOD(ROWNUM, 1000)+ 1                 ORDER_QTY
    ,  LPAD(ROUND(DBMS_RANDOM.VALUE(1, 10000)), 5, '0') ORDER_CD
FROM DUAL
CONNECT BY LEVEL <= 100000
ORDER BY DBMS_RANDOM.RANDOM();


COMMIT;

CREATE INDEX YOON.IX_T_ORDER42 ON YOON.T_ORDER42(ORDER_CD);

ANALYZE TABLE YOON.T_ORDER42 ESTIMATE STATISTICS SAMPLE 10 PERCENT;

